// A single mock phone: a real HTTP model server (Ollama- or OpenAI-flavored)
// that registers + heartbeats with the orchestrator exactly like a real phone.
// Indistinguishable to the rest of the system. Used for all pre-hardware dev.
import http from 'node:http';
import express from 'express';

const ORCH = process.env.SISYPHUS_ORCH || 'http://127.0.0.1:4100';
const TOK_PER_SEC = 25;
const TOK_MS = Math.round(1000 / TOK_PER_SEC);

// --- canned code generation (valid, passes node --check) -----------------
function cannedAnswer(prompt) {
  const p = String(prompt || '');
  const ext = (p.match(/\.(mjs|js|json|css|html)\b/i) || [, 'js'])[1].toLowerCase();
  const fnMatch = p.match(/function\s+([a-zA-Z_$][\w$]*)/);
  const fn = fnMatch ? fnMatch[1] : 'run';
  if (ext === 'json') return '```json\n{\n  "ok": true,\n  "generated": "sisyphus-mock"\n}\n```';
  if (ext === 'css')
    return '```css\n.card {\n  padding: 1rem;\n  border-radius: 12px;\n  background: #14161d;\n}\n```';
  if (ext === 'html')
    return '```html\n<!doctype html>\n<html>\n  <head><meta charset="utf-8"><title>Mock</title></head>\n  <body><main>ok</main></body>\n</html>\n```';
  // js / mjs
  return (
    '```js\n' +
    `export function ${fn}(input) {\n` +
    '  // generated by sisyphus mock worker\n' +
    '  if (input == null) return null;\n' +
    '  return String(input);\n' +
    '}\n' +
    '```'
  );
}

function tokenize(text) {
  // Split into word-ish chunks so streaming looks like a model emitting tokens.
  return text.match(/\s+|\S+/g) || [text];
}

async function streamTokens(tokens, onToken) {
  for (const t of tokens) {
    onToken(t);
    await new Promise((r) => setTimeout(r, TOK_MS));
  }
}

// --- server --------------------------------------------------------------
export function startMockPhone(opts) {
  const { name, port, runtime = 'cpu', model = 'qwen2.5-coder:3b', proxy = null } = opts;
  const app = express();
  app.use(express.json({ limit: '2mb' }));

  const battery = { pct: 60 + Math.random() * 35 };

  // Health endpoints
  app.get('/api/tags', (_req, res) => res.json({ models: [{ name: model }] }));
  app.get('/v1/models', (_req, res) => res.json({ data: [{ id: model, object: 'model' }] }));

  // Ollama-style chat (NDJSON stream)
  app.post('/api/chat', async (req, res) => {
    const prompt = JSON.stringify(req.body?.messages || '');
    const answer = proxy ? await proxyOllama(proxy, req.body) : cannedAnswer(prompt);
    if (proxy) {
      res.type('application/x-ndjson').send(answer);
      return;
    }
    res.type('application/x-ndjson');
    const tokens = tokenize(answer);
    await streamTokens(tokens, (t) => {
      res.write(
        JSON.stringify({ model, created_at: new Date().toISOString(), message: { role: 'assistant', content: t }, done: false }) + '\n'
      );
    });
    res.write(
      JSON.stringify({
        model,
        created_at: new Date().toISOString(),
        message: { role: 'assistant', content: '' },
        done: true,
        prompt_eval_count: Math.max(8, Math.round(prompt.length / 4)),
        eval_count: tokens.length,
        total_duration: tokens.length * TOK_MS * 1e6,
        eval_duration: tokens.length * TOK_MS * 1e6,
      }) + '\n'
    );
    res.end();
  });

  // OpenAI-style chat (SSE stream) — the NPU endpoint flavor
  app.post('/v1/chat/completions', async (req, res) => {
    const prompt = JSON.stringify(req.body?.messages || '');
    const answer = cannedAnswer(prompt);
    res.set({ 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache', Connection: 'keep-alive' });
    const tokens = tokenize(answer);
    await streamTokens(tokens, (t) => {
      res.write(`data: ${JSON.stringify({ choices: [{ delta: { content: t }, index: 0 }] })}\n\n`);
    });
    res.write(
      `data: ${JSON.stringify({
        choices: [{ delta: {}, index: 0, finish_reason: 'stop' }],
        usage: {
          prompt_tokens: Math.max(8, Math.round(prompt.length / 4)),
          completion_tokens: tokens.length,
          total_tokens: Math.max(8, Math.round(prompt.length / 4)) + tokens.length,
        },
      })}\n\n`
    );
    res.write('data: [DONE]\n\n');
    res.end();
  });

  const server = http.createServer(app);
  return new Promise((resolve) => {
    server.listen(port, '0.0.0.0', async () => {
      const { phoneId } = await registerSelf({ name, port, runtime, model });
      startHeartbeat(phoneId, battery, runtime);
      console.log(`  mock phone "${name}" [${runtime}] on :${port} -> ${phoneId}`);
      resolve({ server, phoneId, name, port, runtime });
    });
  });
}

async function registerSelf({ name, port, runtime, model }) {
  for (let i = 0; i < 20; i++) {
    try {
      const res = await fetch(`${ORCH}/api/phones/register`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({
          name,
          ip: '127.0.0.1',
          port,
          model,
          runtime,
          hw: runtime === 'npu' ? 'Mock Hexagon NPU' : 'Mock Snapdragon (CPU)',
        }),
      });
      if (res.ok) return res.json();
    } catch {
      /* orchestrator not up yet */
    }
    await new Promise((r) => setTimeout(r, 500));
  }
  throw new Error(`mock "${name}" could not reach orchestrator at ${ORCH}`);
}

function startHeartbeat(phoneId, battery, runtime) {
  const tick = async () => {
    battery.pct = Math.max(15, battery.pct - Math.random() * 0.05);
    const busy = Math.random() < 0.3;
    const telemetry = {
      battery: Math.round(battery.pct),
      batteryTempC: +(30 + Math.random() * 8 + (busy ? 4 : 0)).toFixed(1),
      cpuLoad: +(0.1 + Math.random() * 0.3 + (busy ? 0.4 : 0)).toFixed(2),
      memUsedMB: Math.round(3500 + Math.random() * 2000),
      memTotalMB: 16384,
    };
    try {
      await fetch(`${ORCH}/api/phones/${phoneId}/heartbeat`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(telemetry),
      });
    } catch {
      /* ignore */
    }
  };
  tick();
  return setInterval(tick, 3000);
}

async function proxyOllama(base, body) {
  const res = await fetch(`${base}/api/chat`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify(body),
  });
  return res.text();
}
